Data:
  gp_regression:
    eval_indp_target: true
    is_batch_share: false
    is_beta_binomial: false
    is_reuse_across_epochs: false
    max_context: 50
    min_context: 0.0
    n_points: 128
    n_same_samples: 10
    n_samples: 50000
    proba_uniform: 0
    random_targets: false
    range_indcs: null
    save_path: /data/ziz/not-backed-up/chho/gp/gp_dataset.hdf5
    shuffle: false
    test_n_samples: 10000
    train_indp_target: false
    val_n_samples: 0.1
  leo_imagenet:
    data_path: D://embeddings/embeddings
    dataset_name: tieredImageNet
    embedding_crop: center
    model_cls: metafun_classifier
    num_classes: 3
    num_tr_examples_per_class: 2
    num_val_examples_per_class: 2
    shuffle: false
Eval:
  batch_size: 32
  drop_remainder: false
  num_per_epoch: 5000
  validation: true
GPU: 0
Model:
  arch:
    dim_reprs: 128
    embedding_layers: 1
    nn_layers: 3
    nn_size: 128
    num_iters: 5
  comp:
    attention_type: dot_product
    deterministic_decoder: true
    indp_iter: true
    initial_state_type: parametric
    kernel_lengthscale_init: 1.0
    kernel_lengthscale_trainable: true
    kernel_sigma_init: 1.0
    kernel_type: deep_se
    neural_updater_concat_x: false
    no_decoder: false
    repr_as_inputs: false
    stddev_const_scale: 0.1
    use_gradient: false
    use_kernel: true
  ff:
    learnable: false
    num_freq: 10
    stddev_init: 100
    use_ff: true
  latent:
    dim_latent: 64
    num_z_samples: 10
  other:
    initial_inner_lr: 0.1
    repr_as_inputs: false
  reg:
    dropout_rate: 0.0
    l2_penalty_weight: 1.0e-08
    label_smoothing: 0.0
    orthogonality_penalty_weight: 0.001
Train:
  batch_size: 32
  drop_remainder: false
  early_stop:
    early_stop: true
    early_stop_if_increase: false
    early_stop_min_delta: 0
    early_stop_monitor: logprob
    early_stop_patience: 10
    early_stop_reset: false
  epoch: 100
  loss_type: logprob
  lr: 0.0005
  num_per_epoch: 50000
  print_freq: 100
  save:
    ckpt_restore_path: /data/ziz/chho/msc2021/Training
    ckpt_save_dir: /data/ziz/chho/msc2021/Training
    ckpt_save_prefix: null
    restore_from_ckpt: false
    save_final_model: false
  tb_add_log: false
  train_on_val: false
