Data:
  gp_regression:
    eval_indp_target: true
    is_batch_share: false
    is_beta_binomial: false
    is_reuse_across_epochs: false
    max_context: 50
    max_target: null
    min_context: 0.0
    min_target: null
    n_points: 128
    n_same_samples: 10
    n_samples: 50000
    proba_uniform: 0
    random_targets: false
    range_indcs: null
    rescale: true
    save_path: /data/ziz/not-backed-up/chho/gp/gp_dataset.hdf5
    sawtooth:
      freq_range:
      - 3
      - 5
      shift_range:
      - -5
      - 5
      trunc_range:
      - 10
      - 20
    shuffle: false
    test_n_samples: 10000
    train_indp_target: false
    val_n_samples: 0.1
  leo_imagenet:
    data_path: /data/ziz/not-backed-up/chho/embeddings
    dataset_name: tieredImageNet
    embedding_crop: center
    model_cls: metafun_classifier
    num_classes: 5
    num_tr_examples_per_class: 1
    num_val_examples_per_class: 1
    shuffle: false
Eval:
  batch_size: 100
  drop_remainder: false
  num_per_epoch: 100
  validation: true
GPU: 0
Model:
  arch:
    decoder_output_sizes: null
    dim_reprs: 128
    embedding_layers: 1
    nn_layers: 2
    nn_size: 128
    num_iters: 3
  comp:
    attention_type: dot_product
    deterministic_decoder: false
    fixed_sigma_epoch: -1
    fixed_sigma_value: 0.01
    indp_iter: false
    initial_state_type: constant
    kernel_lengthscale_init: 1.0
    kernel_lengthscale_trainable: true
    kernel_sigma_init: 1.0
    kernel_type: deep_se
    neural_updater_concat_x: true
    no_decoder: false
    repr_as_inputs: false
    stddev_const_scale: 0.1
    stddev_offset: 0.0
    use_gradient: false
    use_kernel: false
  ff:
    learnable: false
    num_freq: 10
    stddev_init: 10
    use_ff: false
  latent:
    dim_latent: 64
    num_z_samples: 10
  other:
    initial_inner_lr: 1.0
    nonlinearity: relu
    repr_as_inputs: false
  reg:
    dropout_rate: 0.123
    l2_penalty_weight: 1.92e-09
    label_smoothing: 0.1
    orthogonality_penalty_weight: 0.00137
Train:
  batch_size: 12
  drop_remainder: false
  early_stop:
    early_stop: true
    early_stop_if_increase: false
    early_stop_min_delta: 0
    early_stop_monitor: metric
    early_stop_patience: 45
    early_stop_reset: false
  epoch: 45
  loss_type: null
  lr: 5.55e-05
  num_per_epoch: 2000
  print_freq: 200
  save:
    ckpt_restore_path: /data/ziz/chho/msc2021/Training
    ckpt_save_dir: /data/ziz/chho/msc2021/Training
    ckpt_save_prefix: null
    restore_from_ckpt: false
    save_final_model: false
  tb_add_log: false
  train_on_val: true
