Data:
  gp_regression:
    eval_indp_target: true
    is_batch_share: false
    is_beta_binomial: false
    is_reuse_across_epochs: false
    max_context: 50
    min_context: 0.0
    n_points: 128
    n_same_samples: 10
    n_samples: 50000
    proba_uniform: 0
    random_targets: false
    range_indcs: null
    save_path: /data/ziz/not-backed-up/chho/gp/gp_dataset.hdf5
    shuffle: false
    test_n_samples: 10000
    train_indp_target: false
    val_n_samples: 0.1
  leo_imagenet:
    data_path: /data/ziz/not-backed-up/chho/embeddings
    dataset_name: tieredImageNet
    embedding_crop: center
    model_cls: metafun_classifier
    num_classes: 3
    num_tr_examples_per_class: 2
    num_val_examples_per_class: 2
    shuffle: false
Eval:
  batch_size: 2
  drop_remainder: false
  num_per_epoch: 2
  validation: true
GPU: 0
Model:
  arch:
    dim_reprs: 64
    embedding_layers: 1
    nn_layers: 3
    nn_size: 64
    num_iters: 2
  comp:
    attention_type: dot_product
    deterministic_decoder: true
    indp_iter: false
    initial_state_type: parametric
    kernel_lengthscale_init: 1.0
    kernel_lengthscale_trainable: true
    kernel_sigma_init: 1.0
    kernel_type: deep_se
    neural_updater_concat_x: true
    no_decoder: false
    repr_as_inputs: false
    stddev_const_scale: 0.1
    use_gradient: false
    use_kernel: true
  ff:
    learnable: false
    num_freq: 10
    stddev_init: 10
    use_ff: false
  latent:
    dim_latent: 64
    num_z_samples: 10
  other:
    initial_inner_lr: 1.0
    repr_as_inputs: false
  reg:
    dropout_rate: 0.0
    l2_penalty_weight: 1.0e-08
    label_smoothing: 0.0
    orthogonality_penalty_weight: 0.001
  rff:
    dim_init: 100
    dim_pre_tr: 128
    init_distr: normal
    init_distr_param: {}
    init_trainable: true
    isab_n_induce_points: 50
    mapping: deepset1
    n_layers: 3
    perm_equi_pool_fn: mean
    sab_nn_layers: 3
    sab_num_heads: 4
    transform_dim: null
    weight_trainable: false
Train:
  batch_size: 2
  drop_remainder: false
  early_stop:
    early_stop: false
    early_stop_if_increase: true
    early_stop_min_delta: 0
    early_stop_monitor: metric
    early_stop_patience: 100
    early_stop_reset: false
  epoch: 5
  loss_type: logprob
  lr: 0.001
  num_per_epoch: 3
  print_freq: 1
  save:
    ckpt_restore_path: /data/ziz/chho/msc2021/debug
    ckpt_save_dir: /data/ziz/chho/msc2021/debug
    ckpt_save_prefix: null
    restore_from_ckpt: false
    save_final_model: false
  tb_add_log: false
  train_on_val: false
