Data:
  gp_regression:
    eval_indp_target: true
    is_batch_share: false
    is_beta_binomial: false
    is_reuse_across_epochs: false
    max_context: 50
    min_context: 0.0
    n_points: 128
    n_same_samples: 10
    n_samples: 50000
    proba_uniform: 0
    range_indcs: null
    save_path: ''
    shuffle: false
    test_n_samples: 10000
    train_indp_target: false
    val_n_samples: 0.1
  leo_imagenet:
    data_path: C://Users/hcw10/OneDrive/Documents/Oxford/Courses/Dissertation/Other/embeddings
    dataset_name: tieredImageNet
    embedding_crop: center
    model_cls: metafun_classifier
    num_classes: 1
    num_tr_examples_per_class: 1
    num_val_examples_per_class: 15
    shuffle: false
Eval:
  batch_size: 16
  drop_remainder: false
  num_per_epoch: 2
  validation: false
GPU: null
Model:
  arch:
    dim_reprs: 64
    embedding_layers: 1
    nn_layers: 3
    nn_size: 64
    num_iters: 1
  comp:
    attention_type: dot_product
    deterministic_decoder: true
    indp_iter: false
    initial_state_type: zero
    kernel_lengthscale_init: 1.0
    kernel_sigma_init: 1.0
    kernel_type: se
    neural_updater_concat_x: true
    no_decoder: false
    reprs_as_inputs: false
    stddev_const_scale: 0.1
    use_gradient: false
    use_kernel: false
  ff:
    learnable: false
    num_freq: 10
    stddev_init: 10
    use_ff: false
  rff:
    dim_init: 100
    n_layers: 3
    perm_equi_pool_fn: mean
    mapping: "SAB"
    sab_dim_pre_tr: 128
    sab_nn_layers: 3
    sab_num_heads: 4
    isab_n_induce_points: 50
  other:
    initial_inner_lr: 1.0
    repr_as_inputs: false
  reg:
    dropout_rate: 0.0
    l2_penalty_weight: 1.0e-08
    label_smoothing: 0.0
    orthogonality_penalty_weight: 0.001
Train:
  batch_size: 16
  drop_remainder: false
  early_stop:
    early_stop: false
    early_stop_if_increase: true
    early_stop_min_delta: 0
    early_stop_monitor: acc
    early_stop_patience: 100
    early_stop_reset: false
  epoch: 2
  loss_type: logprob
  lr: 0.001
  num_per_epoch: 3
  print_freq: 1
  save:
    ckpt_restore_path: ./checkpoint
    ckpt_save_dir: null
    ckpt_save_prefix: null
    restore_from_ckpt: false
    save_final_model: false
  train_on_val: false
